- adpyke.codesnap
- antfu.browse-lite
- antfu.iconify
- antfu.unocss
- bierner.markdown-preview-github-styles
- dbaeumer.vscode-eslint
- eamodio.gitlens
- edonet.vscode-command-runner
- esbenp.prettier-vscode
- Gruntfuggly.todo-tree
- lacroixdavid1.vscode-format-context-menu
- mcright.auto-save
- mikestead.dotenv
- mrmlnc.vscode-scss
- ms-playwright.playwright
- ms-vsliveshare.vsliveshare
- pkief.material-icon-theme
- rust-lang.rust-analyzer
- ryuta46.multi-command
- slevesque.vscode-multiclip
- streetsidesoftware.code-spell-checker
- TabNine.tabnine-vscode
- tamasfe.even-better-toml
- usernamehw.errorlens
- vue.volar
- vue.vscode-typescript-vue-plugin
- wmaurer.change-case
