# Spellcheck / autosave delays
feedback_debounce_ms: 300

# Paths excluded from search / spellcheck / todo tags
search_exclude_paths:
  - '.DS_Store'
  - '.git'
  - '.idea'
  - '.vscode'
  - 'coverage'
  - 'dist'
  - 'node_modules'
  - '*.svg'
  - '*.zsh'
  - 'package.json'
  - 'package-lock.json'
  - 'pnpm-lock.yaml'
  - 'yarn.lock'
  - 'Cargo.lock'

preferred_vite_port: 4343

# Disable autosave for specific languages
# e.g. to prevent unwanted Hot-Module-Reloads
disable_autosave_languages:
  - scss
  - typescript
  - vue

# A heavy shell startup configuration can cause Command Runner to paste
# a command before the terminal is ready, thus not running the operation at all
# This can be handled via launching commands with a delay or using
# Powerlevel10k ZSH plugin (or both)
shell_warmup_ms: 50
